name: monify
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.3.3
  - pip
  - pip:
    - Flask-SQLAlchemy==3.0.5
    - Flask-Login==0.6.3
    - Flask-WTF==1.1.1
    - WTForms==3.0.1
    - Werkzeug==2.3.7
    - Jinja2==3.1.2
    - python-dateutil==2.8.2
    - email-validator==2.0.0
